### ISSUE TITLE
dyld: Library not loaded:

### ISSUE THREAD

**Issue by borg** [elliotwoods/ofxSquashBuddies#2] opened 2016-02-18 22:40 UTC
```
dyld: Library not loaded: /Users/satoruhiga/Documents/openFrameworks/of_v0.9.0_osx_release/addons/ofxSquash/build/squash/build/plugins/brieflz/libsquash0.8-plugin-brieflz.dylib
  Referenced from: /Volumes/BORG/....../Sketches/exampleReceivePixels/bin/SquashBuddiesDebug.app/Contents/MacOS/SquashBuddiesDebug
```

When search paths have been set up properly it crashes after successfully compiled. I'm assuming these hard coded paths aren't supposed to be here. 
That aside though, are all these dynlibs supposed to be required and included inside Xcode, i.e. the fact that they are in a bin folder should not be understood to mean they are supposed to go inside the oF bin folder right?

**Comment by elliotwoods** [comment] 2016-02-19 05:40
@borg - the plugins aren't supposed to be linked by XCode at link time, but by the application at run time. 

We spoke with Squash to add an API for setting search paths, which is what we use now
https://github.com/quixdb/squash/issues/187

implemented at:
https://github.com/elliotwoods/ofxSquash/blob/master/src/ofxSquash/Initializer.cpp#L13

It seems like the search path parameter didn't quite work out somehow on the OSX side, and the squash library is ignoring the search path and using the hardcoded path.

@satoruhiga - any ideas here?
maybe we have an old squash lib in the repo which doesn't support the search path?

**Comment by satoruhiga** [comment] 2016-02-19 07:52
Are you added plugins directory in Xcode project?

I think the problem is weird OSX dynamic linking system. (something like install_name or rpath)
but in this case, We want to dylib as plugin. not dynamic library. So we no need to link dylibs to your app.

Can you remove dylibs from your Xcode project?

if solved, add this to README.md -> **You don't add dylibs to Xcode project!**

**Comment by borg** [comment] 2016-02-19 18:27
Ahh...thanks for clarifying. Adding plugins folder from libs/bin/squash/... on the same level as the data folder makes it find the codec. The dyld linker error disappears. 

I got send/receive pixel working on same machine, but only got 1 frame successfully across a busy local network and not able to send across a dedicated MacMini adhoc network. Any additional requirements to make that happen? This is so exciting.

**Comment by satoruhiga** [comment] 2016-02-21 05:56
@borg you mean the ad hoc network is wifi?

I think SquashBuddies doesn't work on wifi because too much packet loss in wifi network.
SquashBuddies uses UDP socket for low latency communication. a UDP socket doesn't have error correction.

if you want sending image over wifi you can use TCP something like http://techlife.sg/TCPSyphon/ http://techlife.sg/TCPSpout/

**Comment by elliotwoods** [comment] 2016-03-10 09:15
this has been resolved in ofxSquash. please pull latest for that repo

**Closed as completed by elliotwoods** 2016-03-10 09:15 UTC
